### PR TITLE
#251 Don't set env vars in tests.

### LINKED ISSUE #251: Update all tests to set the environment variables that they require
Currently, some tests explicitly specify the environment variables that will be needed and some tests assume that these variables are already set. Even if a target is added to the Makefile to set the required variables, we'd still have the case where someone is trying to run a test from the IDE or just using pytest and then the required variables would not be set.

We should likely update the tests so that they read the environment variables to be used from a file or something like that.

### PR DESCRIPTION
**Pull request by kabir**
Users should set these before running them.
Add coarse validation that they have done so for the most important ones

Fixes #251

### CODE REVIEW

**Comment by fjuma** [comment]
@kabir CI finally ran on this one. I'm seeing these assertion errors:

```
>       assert value, f"Need to set the {var_name} environment variable"
E       AssertionError: Need to set the MODEL_PATH environment variable
```

**Comment by kabir** [comment]
@fjuma Ah that is one of the ones we currently disable on CI. 

I either need to:
* Add a bogus values for MODEL_PATH and MODEL_NAME to the CI workflow
* Remove MODEL_PATH and MODEL_NAME from the environment variable names we check for

Any preference?

**Comment by fjuma** [comment]
@kabir I think let's remove MODEL_PATH and MODEL_NAME from the environment variable names we check for. The tests would need to be updated to be able to make use of them anyway.

**Comment by kabir** [comment]
@fjuma done

**Review by fjuma — APPROVED** [review]
Thanks @kabir!

**Pull request merged**
