### PR TITLE
Introduce a new WiseAgentCollaborationType to be used for chat bot agents

### PR DESCRIPTION
**Pull request by fjuma**
Follow up fixes for https://github.com/wise-agents/wise-agents/issues/281 as discussed https://github.com/wise-agents/wise-agents/pull/292#discussion_r1763579016.

This PR:

* Updates `PassThroughClientAgent` to just implement `process_request` (this is the method that most agent implementations will implement and retrieving conversation history and the updates to it will be handled automatically by the default `handle_request` implementation depending on the collaboration type in use). 
* For now, I've updated `ChatAgent` and `AssistantAgent` to implement `handle_request` since they both require implementations that are different from the default implementation where conversation history is only retrieved/updated for the phased collaboration case. If we want to make use of the default `handle_request` implementation for these, we could consider introducing a new enum type, e.g., `WiseAgentCollaborationType.CHAT` or something and update `handle_request` to do the same things that are currently only done for the phased collaboration case for the chat case as well. Then `ChatAgent` and `AssistantAgent` would just need to implement the `process_request` method as usual.

### CODE REVIEW

**Review by maeste — CHANGES_REQUESTED** [review]
I think the proposal to have  WiseAgentCollaborationType.CHAT  could be very useful for many user case, so I would ask you to go on with your proposal.

BTW both this PR and the previous one doesn't have any documentation in our docs. Considering it is a very important part framework user should consider when implementing their own custom agents, I think it would be great to have some kind of documentation, ideally an "how-to code your own agent". It's fine to don't include these docs in this PR, because most likely they would need also an example to show how to use it. But please open an issue for docs and one (or the same if you feel they should go together) for an example.

**Comment by fjuma** [comment]
@maeste I've updated this PR to introduce the new `WiseAgentCollaborationType.CHAT` and I've created an issue to track adding a documentation and example for creating a custom agent (see https://github.com/wise-agents/wise-agents/issues/301).

The `memory_agentic_chatbot` example works as expected with these changes.

But there's one more thing to address here. The `simple_agentic_chatbot` currently makes use of an `LLMOnlyWiseAgent`. I had updated all of our agent implementations so that they make use of the handle_request default implementation. So now that we have updated `AssistantAgent` to set the collaboration type to CHAT, this means that the `LLMOnlyWiseAgent` now receives a non-empty conversation history and so it makes use of it as shown here:

https://github.com/wise-agents/wise-agents/blob/main/src/wiseagents/agents/utility_wise_agents.py#L164-L167

We have a couple options:

1. Introduce a new simple agent type in the utility module that doesn't make use of the conversation history that's passed into its process_request method 

2. Update LLMOnlyWiseAgent to not make use of the conversation_history in its process_request method

Currently, LLMOnlyWiseAgent is used in tests for things like sequential and phased collaboration.

**Comment by maeste** [comment]
> @maeste I've updated this PR to introduce the new `WiseAgentCollaborationType.CHAT` and I've created an issue to track adding a documentation and example for creating a custom agent (see #301).
> 
> The `memory_agentic_chatbot` example works as expected with these changes.
> 
> But there's one more thing to address here. The `simple_agentic_chatbot` currently makes use of an `LLMOnlyWiseAgent`. I had updated all of our agent implementations so that they make use of the handle_request default implementation. So now that we have updated `AssistantAgent` to set the collaboration type to CHAT, this means that the `LLMOnlyWiseAgent` now receives a non-empty conversation history and so it makes use of it as shown here:
> 
> https://github.com/wise-agents/wise-agents/blob/main/src/wiseagents/agents/utility_wise_agents.py#L164-L167
> 
> We have a couple options:
> 
> 1. Introduce a new simple agent type in the utility module that doesn't make use of the conversation history that's passed into its process_request method
> 2. Update LLMOnlyWiseAgent to not make use of the conversation_history in its process_request method
> 
> Currently, LLMOnlyWiseAgent is used in tests for things like sequential and phased collaboration.

Well I removed that example with my last PR #302 (before reading this comment), because it doesn't make a lot of sense for users. I'll add another example with the chat collaboration (but using groq), just to give people the opportunity to test wise-agents with a remote llm. Then I'll focus on examples more significant for users using seq and phased coordination

**Comment by fjuma** [comment]
> > @maeste I've updated this PR to introduce the new `WiseAgentCollaborationType.CHAT` and I've created an issue to track adding a documentation and example for creating a custom agent (see #301).
> > The `memory_agentic_chatbot` example works as expected with these changes.
> > But there's one more thing to address here. The `simple_agentic_chatbot` currently makes use of an `LLMOnlyWiseAgent`. I had updated all of our agent implementations so that they make use of the handle_request default implementation. So now that we have updated `AssistantAgent` to set the collaboration type to CHAT, this means that the `LLMOnlyWiseAgent` now receives a non-empty conversation history and so it makes use of it as shown here:
> > https://github.com/wise-agents/wise-agents/blob/main/src/wiseagents/agents/utility_wise_agents.py#L164-L167
> > We have a couple options:
> > 
> > 1. Introduce a new simple agent type in the utility module that doesn't make use of the conversation history that's passed into its process_request method
> > 2. Update LLMOnlyWiseAgent to not make use of the conversation_history in its process_request method
> > 
> > Currently, LLMOnlyWiseAgent is used in tests for things like sequential and phased collaboration.
> 
> Well I removed that example with my last PR #302 (before reading this comment), because it doesn't make a lot of sense for users. I'll add another example with the chat collaboration (but using groq), just to give people the opportunity to test wise-agents with a remote llm. Then I'll focus on examples more significant for users using seq and phased coordination So, if you merge #302 and rebase this one, you can safely remove the HOLD label and we can go on merging this as is

#302 has been merged, I've rebased and removed the HOLD label here.

**Review by maeste — APPROVED** [review]

**Pull request merged**
